export const ADD_CHECKLIST = 'ADD_CHECKLIST';
export const REMOVE_CHECKLIST = 'REMOVE_CHECKLIST';

export const ADD_CURRENT_USER = 'ADD_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';

export const ADD_COLLABORATION = 'ADD_COLLABORATION';
export const REMOVE_COLLABORATION = 'REMOVE_COLLABORATION';

export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const IS_FETCHING = 'IS_FETCHING';

export const LOGOUT = 'LOGOUT';