export const ADD_CHECKLIST = 'ADD_CHECKLIST';
export const RENAME_CHECKLIST = 'RENAME_CHECKLIST';
export const SET_STATUS_CHECKLIST = 'SET_STATUS_CHECKLIST';
export const DELETE_CHECKLIST = 'DELETE_CHECKLIST';
export const ADD_ITEM = 'ADD_ITEM_CHECKLIST';
export const RENAME_ITEM_CHECKLIST = 'RENAME_ITEM_CHECKLIST';
export const SET_STATUS_ITEM_CHECKLIST = 'SET_STATUS_ITEM_CHECKLIST';
export const DELETE_ITEM_CHECKLIST = 'DELETE_ITEM_CHECKLIST';

export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const ADD_CURRENT_USER = 'ADD_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';

export const AWAITING_REQUEST = 'AWAITING_REQUEST';