import {
  ADD_CHECKLIST,
  RENAME_CHECKLISTADD_CHECKLIST,
  SET_STATUS_CHECKLISTADD_CHECKLIST,
  DELETE_CHECKLISTADD_CHECKLIST,
  ADD_ITEM_CHECKLISTADD_CHECKLIST,
  RENAME_ITEM_CHECKLISTADD_CHECKLIST,
  SET_STATUS_ITEM_CHECKLISTADD_CHECKLIST,
  DELETE_ITEM_CHECKLISTADD_CHECKLIST,
} from './actionTypes';

export const addChecklist = checklist => ({
  type: ADD_CHECKLIST,
  payload: {
    checklist
  }
})